### ISSUE TITLE
Problem in plotting the data

### ISSUE THREAD

**Issue by pimakshay** [Universite-Gustave-Eiffel/NoisePlanet#100]
Hi Everyone
I am a masters student pursuing my masters degree in Computational Science and Engineering at TUM, Germany.
I am trying to use the noiseplanet library for one of my projects and was making myself comfortable by following the example test cases. The example test case ([Link](https://github.com/arthurdjn/noiseplanet/blob/master/test/test_matching.py)) with the track data worked perfectly fine.
1. However when I passed the track data generated by my code, it was not able to plot the results.

I tried debugging the files but I was not able to figure out why the variables "track" and "track_corr" had different sizes after applying the hmm model. Please find the attached screenshot for more details.

Shapes are as below
"track": 66, 2
 "track_corr": 46, 2

2. Can you also give some idea on the variable "dist" in ox.graph_from_point and what value should be good to avoid such errors in real time?
![Screenshot](https://user-images.githubusercontent.com/58036792/162900559-ff78f59b-4ec8-4115-94b7-d97303398fc8.png)

Thank you!

**Comment by gpetit** [comment]
Hi @pimakshay and thanks for your interest in NoiseCapture.

The code you are following is not part of Noise-Planet repo. It has been developed by @arthurdjn as part of an engineering school (really great) project.

If I'm not wrong, `track` and `track_corr` are not the same since a correction is applied to project the GPS trajectory onto existing roads (from OSM).

Maybe @arthurdjn would be able to complete / help ?
